sudo: false
language: erlang
otp_release:
  - 17.5
addons:
  apt:
    packages:
      - xsltproc
env:
  - BUILD_DIR=$HOME/rabbitmq-public-umbrella CONSUL_VERSION=0.5.2 RABBIT_TAG=rabbitmq_v3_5_6
install:
  - "$TRAVIS_BUILD_DIR/travis-umbrella-setup.sh"
  - "$TRAVIS_BUILD_DIR/travis-install-consul.sh"
script: cd $BUILD_DIR/autocluster && make test
before_deploy:
  - cd $BUILD_DIR/autocluster
  - VERSION=$TRAVIS_TAG make
  - mkdir -p $HOME/dpl
  - cd $HOME/dpl
cache:
  apt: true
  directories:
  - "$HOME/consul"
  - "$BUILD_DIR"
deploy:
  provider: releases
  api_key: 294f047eeb1e2461acc155d6728405daf7609271
  file: "$BUILD_DIR/autocluster/dist/autocluster-${TRAVIS_TAG}.ez"
  on:
    tags: true
    repo: aweber/rabbitmq-autocluster
